### ISSUE TITLE
Can't add panels to frame?

### ISSUE THREAD

**Issue by czaarek99** [DarkStorm652/Minecraft-GUI-API#7]
Did I misunderstand how a panel should be used? Isn't it like a subcategory of items? So you might have a frame with a bunch of panels that sort toggles into categories.

https://gist.github.com/anonymous/5fe54d73e7e9e86cc40b

**Comment by masl123** [comment]
Hi,
have a look at this:
https://github.com/masl123/mp3Jukebox/blob/master/src/main/java/com/masl/mp3JUKEBOX/OptionsGui.java 
This is a Simple Implementation of a AbstractGuiManager. The first few lines of the setup method (74-87) and the last few lines (169-183) are the most important
- Did you set a Theme with setTheme(new SimpleTheme())?
- Did you set a LayoutManager with setLayoutManager(mgr)?

BTW: For the Slider to Work, you need subscribe the tickEvent and call the Update Method in your GUI Manager (AbstractGuiManager).

These Panels are a bit like the Java Swing Panels.
You can send me a bit of your Code, so maybe I can help you.
--Masl

**Comment by czaarek99** [comment]
I can use everything else properly and it works, the only problem I encounter is with the panel in the createTestFrame. Here is my code:
https://gist.github.com/anonymous/6c6a86ceeeb94ccb7d1a

**Comment by masl123** [comment]
You are calling  "Dimension defaultDimension = theme.getUIForComponent(textFrame).getDefaultSize(textFrame);" in line 219 and 243. 
The getTheme Method returns "null", because the Theme attribute has not been set. So you get a NullPointerException.

Simply call "setTheme(new SimpleTheme());"  at the beginning, right after the "is already Setup" check, in your setup method, so getTheme() does return a Object and not Null, and you should be fine. 

BTW: I think, you also dont need to set the Theme for all Components, simply set it Once for the FlameGuiManager. (I at least did not do it, and it Works)

**Comment by czaarek99** [comment]
Thank you, solved my issue.
